// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1LPk6KpKxjKiHOtq-n9Tgs_orNGWJqFw',
    appId: '1:624062743865:web:2825852d52ff6b55cf54e8',
    messagingSenderId: '624062743865',
    projectId: 'loactionapp-3c198',
    authDomain: 'loactionapp-3c198.firebaseapp.com',
    storageBucket: 'loactionapp-3c198.appspot.com',
    measurementId: 'G-FF0JZM1S18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgLs_Fg1oEviUodvS9UjBZPXz8Oju9XCU',
    appId: '1:624062743865:android:bbc3ad8a3b5469b1cf54e8',
    messagingSenderId: '624062743865',
    projectId: 'loactionapp-3c198',
    storageBucket: 'loactionapp-3c198.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtD3dROC-jaSgjkJeLnKZE61GgF0NIKWU',
    appId: '1:624062743865:ios:dfd15066beca5eadcf54e8',
    messagingSenderId: '624062743865',
    projectId: 'loactionapp-3c198',
    storageBucket: 'loactionapp-3c198.appspot.com',
    iosBundleId: 'com.example.locationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtD3dROC-jaSgjkJeLnKZE61GgF0NIKWU',
    appId: '1:624062743865:ios:82c0f6ec01f0cc26cf54e8',
    messagingSenderId: '624062743865',
    projectId: 'loactionapp-3c198',
    storageBucket: 'loactionapp-3c198.appspot.com',
    iosBundleId: 'com.example.locationApp.RunnerTests',
  );
}
